---
title: "Iteration and List Columns"
author: "Chenyu Jin"
date: "2024-10-24"
output: github_document
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
```

Here are some lists:

```{r}
l = list(
  vec_numeric = 1:4,
  unif_sample =  runif(100),
  mat         = matrix(1:8, nrow = 2, ncol = 4, byrow = TRUE),
  summary     = summary(rnorm(1000)))

l[["mat"]]
```

Make a useful list:

```{r}
list_norms = 
  list(
    a = rnorm(20, 0, 5),
    b = rnorm(20, 4, 5),
    c = rnorm(20, 0, 10),
    d = rnorm(20, 4, 10)
  )
```

Try the function I wrote last time:

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  out_df = 
    tibble(
    mean = mean_x, 
    sd = sd_x
  )
  
  return(out_df)
}
```

```{r}
mean_and_sd(list_norms[["a"]])
mean_and_sd(list_norms[["b"]])
mean_and_sd(list_norms[["c"]])
mean_and_sd(list_norms[["d"]])
```

# Use a for loop

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norms[[i]])
  
}
```

# Use map to do the same thing

```{r}
output = map(list_norms, mean_and_sd)
```

Do other things

```{r}
output = map_dfr(list_norms, mean_and_sd)

output = map(list_norms, IQR)
```

## LIST COLUMNS!!!

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    samp = list_norms
  )

listcol_df

mean_and_sd(listcol_df[["samp"]][["a"]])
mean_and_sd(listcol_df[["samp"]][["b"]])
mean_and_sd(listcol_df[["samp"]][["c"]])
mean_and_sd(listcol_df[["samp"]][["d"]])

map(listcol_df[["samp"]], mean_and_sd)
```

ADD A LIST COLUMN!!!

```{r}
new_df = listcol_df |>
  mutate(output = map(samp, mean_and_sd),
         iqr = map_dbl(samp, IQR))

new_df = listcol_df |>
  mutate(output = map(samp, mean_and_sd),
         iqr = map_dbl(samp, IQR)) |>
  select(-samp) |>
  unnest(output)
```

# Revisiting NSDUH

```{r}
nsduh_table <- function(html, table_num) {
  
  table = 
    html |> 
    html_table() |> 
    nth(table_num) |>
    slice(-1) |> 
    select(-contains("P Value")) |>
    pivot_longer(
      -State,
      names_to = "age_year", 
      values_to = "percent") |>
    separate(age_year, into = c("age", "year"), sep = "\\(") |>
    mutate(
      year = str_replace(year, "\\)", ""),
      percent = str_replace(percent, "[a-c]$", ""),
      percent = as.numeric(percent)) |>
    filter(!(State %in% c("Total U.S.", "Northeast", "Midwest", "South", "West")))
  
  table
}

nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = read_html(nsduh_url)

# Using for loop:

output = vector("list", 3)

for (i in c(1, 4, 5)) {
  output[[i]] = nsduh_table(nsduh_html, i)
}

nsduh_results = bind_rows(output)

# Using map:

nsduh_results = 
  map(c(1, 4, 5), nsduh_table, html = nsduh_html) |> 
  bind_rows()

# Using data frames and list columns:

nsduh_results= 
  tibble(
    name = c("marj", "cocaine", "heroine"),
    number = c(1, 4, 5)) |> 
  mutate(table = map(number, \(num) nsduh_table(html = nsduh_html, num))) |> 
  unnest(cols = "table")
```

# Operations on nested data

